packages:
  - apps/*
  - packages/*
allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
  onnxruntime-node: false
  protobufjs: true
  sharp: true
  workerd: true

overrides:
  "fast-uri@3": "^3.1.4"
  "fast-uri@4": "^4.1.1"
  sharp: ">=0.35.0"
