import { randomUUID } from "node:crypto";
import type { ForgeJob } from "./contracts.js";

const BLOCKED_PATTERNS: Array<[RegExp, string]> = [
  [/child_process|\bexec\s*\(/, "Generated connector may execute arbitrary commands."],
  [/process\.env|\.env\b/, "Generated connector may access process secrets."],
  [
    /https?:\/\/(?!api\.github\.com|api\.linear\.app|sentry\.io)/,
    "Generated connector references a non-allowlisted network endpoint.",
  ],
  [/eval\s*\(|new Function/, "Generated connector uses dynamic evaluation."],
  [/rm\s+-rf|DROP\s+TABLE/i, "Generated connector includes a destructive command."],
];

const PROMPT_SECRET_PATTERNS = [
  /\bsk-[A-Za-z0-9_-]{10,}\b/g,
  /\b(?:gh[pousr]_[A-Za-z0-9_]{10,}|github_pat_[A-Za-z0-9_]{10,})\b/g,
  /\bBearer\s+[^\s,;]+/gi,
  /\b(?:api[_-]?key|token|secret|password)\s*[:=]\s*[^\s,;]+/gi,
];

export function redactForgePrompt(prompt: string): string {
  return PROMPT_SECRET_PATTERNS.reduce(
    (redacted, pattern) => redacted.replace(pattern, "[REDACTED]"),
    prompt,
  );
}

function requestedScopes(prompt: string): string[] {
  const lower = prompt.toLowerCase();
  const scopes = ["events:read"];
  if (lower.includes("github")) scopes.push("github:read");
  if (lower.includes("linear")) scopes.push("linear:read");
  if (lower.includes("sentry")) scopes.push("sentry:read");
  const explicitlyReadOnly = /\bread[- ]only\b|\bno[- ]write\b|\bwithout writes?\b/.test(lower);
  const providerWriteIntent =
    /\b(?:create|open)\s+(?:an?\s+)?(?:issue|comment|pull request|pr)\b|\bwrite to (?:github|linear|sentry|provider)\b|\bpost (?:a\s+)?comment\b|\bdeploy\b/.test(
      lower,
    );
  if (!explicitlyReadOnly && providerWriteIntent) scopes.push("provider:write");
  return scopes;
}

function connectorSource(prompt: string, scopes: string[]): string {
  return (
    `/** Generated by EventForge Forge Studio. Review before installation. */\n` +
    `export const manifest = ${JSON.stringify({ name: "forged-connector", requestedScopes: scopes }, null, 2)} as const;\n\n` +
    `export async function handleEvent(event: { topic: string; payload: Record<string, unknown> }) {\n` +
    `  // Intent: ${prompt.replace(/\*\//g, "*")}.\n` +
    `  return { summary: \`Received \${event.topic}\`, requiresApproval: true };\n` +
    `}\n`
  );
}

export function scanForgeFiles(files: Array<{ path: string; content: string }>): string[] {
  return files.flatMap((file) =>
    BLOCKED_PATTERNS.flatMap(([pattern, message]) =>
      pattern.test(file.content) ? [`${file.path}: ${message}`] : [],
    ),
  );
}

export function createForgeDraft(workspaceId: string, prompt: string): ForgeJob {
  const safePrompt = redactForgePrompt(prompt);
  const scopes = requestedScopes(safePrompt);
  const files = [
    { path: "src/connector.ts", content: connectorSource(safePrompt, scopes) },
    {
      path: "README.md",
      content: `# Forged connector\n\nIntent: ${safePrompt}\n\nInstallation requires an EventForge owner approval.\n`,
    },
    {
      path: "eventforge.connector.json",
      content: JSON.stringify(
        { version: 1, requestedScopes: scopes, execution: "isolated-process" },
        null,
        2,
      ),
    },
  ];
  const findings = scanForgeFiles(files);
  return {
    id: randomUUID(),
    workspaceId,
    prompt: safePrompt,
    status: findings.length ? "rejected" : "validated",
    requestedScopes: scopes,
    generatedFiles: files,
    validation: { passed: findings.length === 0, findings },
    createdAt: new Date().toISOString(),
  };
}
