{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "eventforge.fullname" . }}-default-deny
spec:
  podSelector: {}
  policyTypes: [Ingress, Egress]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "eventforge.fullname" . }}-ingress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "eventforge.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes: [Ingress]
  ingress:
    - ports:
        - { protocol: TCP, port: {{ .Values.service.port }} }
{{- end }}
