import { describe, expect, it } from "vitest";
import { alert, EvidenceLedger, evaluateGate, gaReady, KillSwitches, launchDefaults, nextStage, publicStatus, reconcile, restorePlan, rollbackAllowed, surfaces, withinErrorBudget, type Evidence, type Gate } from "../src/operational-readiness.js";
const now = 1_000_000; const gate = (surface = "console_api") => ({ surface, ...launchDefaults[surface as keyof typeof launchDefaults] }) as Gate;
const passed = (surface = "console_api", result: Evidence["result"] = "passed"): Evidence => ({ id: surface, surface: surface as Evidence["surface"], result, observedAt: now, kind: "probe", correlationId: "safe-1" });
describe("operational readiness", () => {
  it("evaluates monthly error budgets and retains independent append-only evidence", () => { expect(withinErrorBudget(999, 1000, 99.9)).toBe(true); expect(withinErrorBudget(998, 1000, 99.9)).toBe(false); const ledger = new EvidenceLedger(); ledger.append(passed()); expect(ledger.records()).toHaveLength(1); expect(() => (ledger.records()[0]!.result = "failed")).toThrow(); });
  it("uses concrete SLO gates and closes only missing, stale, skipped or failed surfaces", () => { expect(evaluateGate(gate(), [], now)).toBe("unknown"); expect(evaluateGate(gate(), [passed()], now + 600_001)).toBe("stale"); expect(evaluateGate(gate(), [passed("console_api", "skipped")], now)).toBe("skipped"); expect(evaluateGate(gate(), [passed()], now)).toBe("passed"); });
  it("requires all upstreams, zero variance and no security veto for GA", () => { const gates = surfaces.map(gate); const evidence = surfaces.map((surface) => passed(surface)); const upstream = Object.fromEntries(gates.flatMap((item) => item.dependencies.map((d) => [d, true]))); expect(gaReady(gates, evidence, upstream, false, 0, false)).toBe(true); expect(gaReady(gates, evidence, upstream, true, 0, false)).toBe(false); });
  it("authorizes kill switches, denies new work, holds accepted work and never falls back", () => { const switches = new KillSwitches(); expect(() => switches.change({ id: "x", roles: ["operator"] }, "signed_ingress", false, "test", now)).toThrow(); switches.change({ id: "sec", roles: ["operator"], mfaAt: now, securityAuthorized: true }, "signed_ingress", false, "test", now); expect(switches.disposition("signed_ingress", false)).toBe("deny_new_work"); expect(switches.disposition("signed_ingress", true)).toBe("held"); });
  it("reconciles duplicate/retry/replay/DLQ provenance exactly and blocks variance", () => { expect(reconcile([{ id: "a", workspaceId: "w", state: "terminal", provenance: "accepted", period: "2026-07" }, { id: "a", workspaceId: "w", state: "duplicate", provenance: "duplicate", period: "2026-07" }, { id: "b", workspaceId: "w", state: "dlq", provenance: "retry", period: "2026-07" }])).toMatchObject({ variance: 1, nonBillable: 2 }); });
  it("keeps public status and alerts payload-free, and constrains rollback/restore", () => { expect(JSON.stringify(publicStatus({ console_api: "failed" }, { summary: "tenant payload stack", updatedAt: "now" }))).not.toMatch(/tenant|payload|stack/); expect(alert("queue_dlq", "warning", "safe-1", "runbook")).toEqual({ category: "queue_dlq", severity: "warning", correlationId: "safe-1", runbook: "runbook" }); expect(rollbackAllowed(false, false, 2)).toMatchObject({ allowed: false, escalate: true, preservesEvidence: true, databaseRewind: false }); expect(restorePlan()).toMatchObject({ isolationFirst: true, rpoMinutes: 15 }); });
  it("never skips stages and resets/demotes on a critical breach", () => { expect(nextStage("staff_canary", 6, 0, 0, false, false)).toBe("staff_canary"); expect(nextStage("staff_canary", 7, 0, 0, false, false)).toBe("design_partners"); expect(nextStage("design_partners", 14, 3, 2, true, false)).toBe("ga_review"); expect(nextStage("design_partners", 3, 3, 2, true, true)).toBe("internal"); });
});
